{"timestamp":"2025-04-27T16:31:16.270458Z","level":"WARN","loggerName":"SampleApp","threadName":"main","message":"This is a warning message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:31:16.270958Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"An error occurred during processing.","throwable":"java.lang.RuntimeException: Something went wrong!\n\tat io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)\n\tat kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)\n\tat kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)\n\tat kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)\n\tat kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)\n","contextData":{}}{"timestamp":"2025-04-27T16:31:16.270681Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"This is an error message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:31:16.270033Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This is an informational message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:31:16.271266Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This uses a lambda for potentially expensive message creation.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:16.554296Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"This is an error message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:16.554385Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"An error occurred during processing.","throwable":"java.lang.RuntimeException: Something went wrong!\n\tat io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)\n\tat kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)\n\tat kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)\n\tat kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)\n\tat kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)\n","contextData":{}}{"timestamp":"2025-04-27T16:42:16.554475Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This uses a lambda for potentially expensive message creation.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:16.554196Z","level":"WARN","loggerName":"SampleApp","threadName":"main","message":"This is a warning message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:16.554002Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This is an informational message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:39.513191Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"This is an error message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:39.513353Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"An error occurred during processing.","throwable":"java.lang.RuntimeException: Something went wrong!\n\tat io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)\n\tat kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)\n\tat kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)\n\tat kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)\n\tat kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)\n","contextData":{}}{"timestamp":"2025-04-27T16:42:39.513576Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This uses a lambda for potentially expensive message creation.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:39.512993Z","level":"WARN","loggerName":"SampleApp","threadName":"main","message":"This is a warning message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T16:42:39.512646Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This is an informational message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:17:03.690969Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This uses a lambda for potentially expensive message creation.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:17:03.690834Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"An error occurred during processing.","throwable":"java.lang.RuntimeException: Something went wrong!\n\tat io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)\n\tat kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)\n\tat kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)\n\tat kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)\n\tat kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)\n","contextData":{}}{"timestamp":"2025-04-27T17:17:03.689598Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This is an informational message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:17:03.690152Z","level":"WARN","loggerName":"SampleApp","threadName":"main","message":"This is a warning message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:17:03.690366Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"This is an error message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:23:27.992839Z","level":"WARN","loggerName":"SampleApp","threadName":"main","message":"This is a warning message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:23:27.993082Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"An error occurred during processing.","throwable":"java.lang.RuntimeException: Something went wrong!\n\tat io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:49)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)\n\tat kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)\n\tat kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)\n\tat kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:14)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)\n","contextData":{}}{"timestamp":"2025-04-27T17:23:27.993176Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This uses a lambda for potentially expensive message creation.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:23:27.992972Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"This is an error message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:23:27.992601Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This is an informational message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:35:44.232814Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"This is an error message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:35:44.232943Z","level":"ERROR","loggerName":"SampleApp","threadName":"main","message":"An error occurred during processing.","throwable":"java.lang.RuntimeException: Something went wrong!\n\tat io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)\n\tat kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)\n\tat kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)\n\tat kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)\n\tat kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:14)\n\tat io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)\n","contextData":{}}{"timestamp":"2025-04-27T17:35:44.233034Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This uses a lambda for potentially expensive message creation.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:35:44.232692Z","level":"WARN","loggerName":"SampleApp","threadName":"main","message":"This is a warning message.","throwable":null,"contextData":{}}{"timestamp":"2025-04-27T17:35:44.232391Z","level":"INFO","loggerName":"SampleApp","threadName":"main","message":"This is an informational message.","throwable":null,"contextData":{}}